name: GitHub CLI
on: [push]
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g pnpm@6.23.6
      - run: pnpm install
      - run: pnpm run typecheck
      - run: pnpm run lint
