name: GitHub CLI
on: [push]
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PNPM
        run: npm install -g pnpm@6.23.6
      - name: Install Dependencies
        run: pnpm install
      - name: Type Check
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
